import { ButtonInteraction } from "discord.js";

import database from "../../features/database";
import reactions from "../../assets/reactions";

/**
 * Handles autorole requests
 * @param i interaction generated by the event listener
 */
const autoroleHandler = async (i: ButtonInteraction) => {
  let guild = await database.guilds.findOne({ id: i.guildId! });
  if (
    !guild?.autorole ||
    !guild.autorole.some((v) => v.messageId === i.message.id)
  )
    return i.reply({ content: `Failed to issue role !`, ephemeral: true });

  let autorole = guild.autorole.find((v) => v.messageId === i.message.id)!;

  let roles = (await i.guild!.members.fetch(i.user.id)).roles;

  if (roles.cache.has(autorole.roleId))
    return i.reply({
      content: `Role already issued`,
      ephemeral: true,
    });

  roles
    .add(autorole.roleId)
    .then(() =>
      i.reply({
        content: `Role issued ${reactions.smile.random}`,
        ephemeral: true,
      })
    )
    .catch(() =>
      i.reply({
        content: `Failed to issue role !`,
        ephemeral: true,
      })
    );
};

export default autoroleHandler;
