name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installation
        run: npm install
      - name: Copying fake config file
        run: cp .env.example .env
      - name: Tests
        run: npm run test
      - name: Build
        run: npm run test
