name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installation
        run: npm install
      - name: Copying fake config files
        run: |
          cp src/config/local.example.ts src/config/local.ts
          cp src/config/secrets.example.ts src/config/secrets.ts
      - name: Tests and Build
        run: |
          npm run test
          npm run build
